package cc.kune.core.client.i18n;

/**
 * Autogenerated by trunk/bin/i18n-db2gwt.sh, please not edit directly
 */
import com.google.gwt.i18n.client.ConstantsWithLookup;

public interface KuneConstants extends ConstantsWithLookup {
}
