INSERT INTO `globalize_languages` VALUES (  15,'aa','ltr','Afar','','','aa','aar','aar','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (  33,'ab','ltr','Abkhazian','','','ab','abk','abk','\0','аҧсуа бызшәа','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES ( 114,'af','ltr','Afrikaans','','','af','afr','afr','\0','Afrikaans','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES ( 191,'ak','ltr','Akan','','','ak','aka','aka','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES ( 247,'am','ltr','Amharic','','','am','amh','amh','\0','አማርኛ','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES ( 340,'ar','rtl','Arabic','','','ar','ara','ara','\0','العربية','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES ( 346,'an','ltr','Aragonese','','','an','arg','arg','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES ( 376,'as','ltr','Assamese','','','as','asm','asm','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES ( 438,'av','ltr','Avaric','','','av','ava','ava','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES ( 441,'ae','ltr','Avestan','','','ae','ave','ave','\0','','','','',NULL,'A');
INSERT INTO `globalize_languages` VALUES ( 483,'ay','ltr','Aymara','','','ay','aym','aym','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES ( 496,'az','ltr','Azerbaijani','','','az','aze','aze','\0','azərbaycan','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES ( 512,'ba','ltr','Bashkir','','','ba','bak','bak','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES ( 514,'bm','ltr','Bambara','','','bm','bam','bam','\0','Bamanankan','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES ( 614,'be','ltr','Belarusian','','','be','bel','bel','\0','Беларуская','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES ( 616,'bn','ltr','Bengali','','','bn','ben','ben','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES ( 721,'bi','ltr','Bislama','','','bi','bis','bis','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES ( 860,'bo','ltr','Tibetan','','','bo','bod','bod','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES ( 875,'bs','ltr','Bosnian','','','bs','bos','bos','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES ( 936,'br','ltr','Breton','','','br','bre','bre','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (1020,'bg','ltr','Bulgarian','','','bg','bul','bul','\0','Български','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (1177,'ca','ltr','Catalan','','','ca','cat','cat','\0','Català','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (1233,'cs','ltr','Czech','','','cs','ces','ces','\0','čeština','','','c%10==1 && c%100!=11 ? 1 : c%10>=2 && c%10<=4 && (c%100<10 || c%100>=20) ? 2 : 3',NULL,'L');
INSERT INTO `globalize_languages` VALUES (1242,'ch','ltr','Chamorro','','','ch','cha','cha','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (1246,'ce','ltr','Chechen','','','ce','che','che','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (1261,'cu','ltr','Slavic','','Church','cu','chu','chu','\0','','','','',NULL,'A');
INSERT INTO `globalize_languages` VALUES (1262,'cv','ltr','Chuvash','','','cv','chv','chv','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (1372,'kw','ltr','Cornish','','','kw','cor','cor','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (1373,'co','ltr','Corsican','','','co','cos','cos','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (1397,'cr','ltr','Cree','','','cr','cre','cre','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (1481,'cy','ltr','Welsh','','','cy','cym','cym','\0','Cymraeg','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (1499,'da','ltr','Danish','','','da','dan','dan','\0','Dansk','','','c == 1 ? 1 : 2',NULL,'L');
INSERT INTO `globalize_languages` VALUES (1556,'de','ltr','German','','','de','deu','deu','\0','Deutsch','','','c == 1 ? 1 : 2',NULL,'L');
INSERT INTO `globalize_languages` VALUES (1607,'dv','ltr','Divehi','','','dv','div','div','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (1760,'dz','ltr','Dzongkha','','','dz','dzo','dzo','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (1793,'el','ltr','Greek','','Modern (1453-)','el','ell','ell','\0','Ελληνικά','','','c == 1 ? 1 : 2',NULL,'L');
/* INSERT INTO `globalize_languages` VALUES (1819,'en','ltr','English','','','en','eng','eng','\0','','','','c == 1 ? 1 : 2','',NULL'); */
INSERT INTO `globalize_languages` VALUES (1831,'eo','ltr','Esperanto','','','eo','epo','epo','\0','','','','c == 1 ? 1 : 2',NULL,'C');
INSERT INTO `globalize_languages` VALUES (1851,'et','ltr','Estonian','','','et','est','est','\0','Eesti','','','c == 1 ? 1 : 2',NULL,'L');
INSERT INTO `globalize_languages` VALUES (1865,'eu','ltr','Basque','','','eu','eus','eus','\0','euskera','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (1869,'ee','ltr','Ewe','','','ee','ewe','ewe','\0','Ɛʋɛ','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (1886,'fo','ltr','Faroese','','','fo','fao','fao','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (1889,'fa','ltr','Persian','','','fa','fas','fas','\0','فارسی','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (1901,'fj','ltr','Fijian','','','fj','fij','fij','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (1903,'fi','ltr','Finnish','','','fi','fin','fin','\0','suomi','','','c == 1 ? 1 : 2',NULL,'L');
INSERT INTO `globalize_languages` VALUES (1930,'fr','ltr','French','','','fr','fra','fra','\0','Français','','','c == 1 ? 1 : 2',NULL,'L');
INSERT INTO `globalize_languages` VALUES (1942,'fy','ltr','Frisian','','','fy','fry','fry','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (1954,'ff','ltr','Fulah','','','ff','ful','ful','\0','Fulfulde, Pulaar, Pular','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (2112,'gd','ltr','Gaelic','Scots','','gd','gla','gla','\0','','','','c==1 ? 1 : c==2 ? 2 : 3',NULL,'L');
INSERT INTO `globalize_languages` VALUES (2115,'ga','ltr','Irish','','','ga','gle','gle','\0','Gaeilge','','','c==1 ? 1 : c==2 ? 2 : 3',NULL,'L');
INSERT INTO `globalize_languages` VALUES (2116,'gl','ltr','Gallegan','','','gl','glg','glg','\0','Galego','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (2125,'gv','ltr','Manx','','','gv','glv','glv','\0','','','','',NULL,'E');
INSERT INTO `globalize_languages` VALUES (2194,'gn','ltr','Guarani','','','gn','grn','grn','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (2226,'gu','ltr','Gujarati','','','gu','guj','guj','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (2304,'ht','ltr','Haitian; Haitian Creole','','','ht','hat','hat','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (2305,'ha','ltr','Hausa','','','ha','hau','hau','\0','Hausa','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (2315,'sh','ltr','Serbo-Croatian','','','sh','','hbs','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (2323,'he','rtl','Hebrew','','','he','heb','heb','\0','עברית','','','c == 1 ? 1 : 2',NULL,'L');
INSERT INTO `globalize_languages` VALUES (2329,'hz','ltr','Herero','','','hz','her','her','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (2343,'hi','ltr','Hindi','','','hi','hin','hin','\0','हिंदी','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (2370,'ho','ltr','Hiri Motu','','','ho','hmo','hmo','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (2418,'hr','ltr','Croatian','','','hr','hrv','hrv','\0','Hrvatski','','','c%10==1 && c%100!=11 ? 1 : c%10>=2 && c%10<=4 && (c%100<10 || c%100>=20) ? 2 : 3',NULL,'L');
INSERT INTO `globalize_languages` VALUES (2443,'hu','ltr','Hungarian','','','hu','hun','hun','\0','Magyar','','','c = 1',NULL,'L');
INSERT INTO `globalize_languages` VALUES (2466,'hy','ltr','Armenian','','','hy','hye','hye','\0','Հայերեն','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (2480,'ig','ltr','Igbo','','','ig','ibo','ibo','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (2494,'io','ltr','Ido','','','io','ido','ido','\0','','','','',NULL,'C');
INSERT INTO `globalize_languages` VALUES (2519,'ii','ltr','Yi','','Sichuan','ii','iii','iii','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (2532,'iu','ltr','Inuktitut','','','iu','iku','iku','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (2539,'ie','ltr','Interlingue','','','ie','ile','ile','\0','','','','',NULL,'C');
INSERT INTO `globalize_languages` VALUES (2556,'ia','ltr','Interlingua','International Auxiliary Language Association','','ia','ina','ina','\0','','','','',NULL,'C');
INSERT INTO `globalize_languages` VALUES (2558,'id','ltr','Indonesian','','','id','ind','ind','\0','Bahasa indonesia','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (2574,'ik','ltr','Inupiaq','','','ik','ipk','ipk','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (2593,'is','ltr','Icelandic','','','is','isl','isl','\0','Íslenska','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (2600,'it','ltr','Italian','','','it','ita','ita','\0','italiano','','','c == 1 ? 1 : 2',NULL,'L');
INSERT INTO `globalize_languages` VALUES (2652,'jv','ltr','Javanese','','','jv','jav','jav','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (2723,'ja','ltr','Japanese','','','ja','jpn','jpn','\0','日本語','','','c = 1',NULL,'L');
INSERT INTO `globalize_languages` VALUES (2763,'kl','ltr','Kalaallisut','','','kl','kal','kal','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (2765,'kn','ltr','Kannada','','','kn','kan','kan','\0','ಕನ್ನಡ','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (2769,'ks','ltr','Kashmiri','','','ks','kas','kas','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (2770,'ka','ltr','Georgian','','','ka','kat','kat','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (2771,'kr','ltr','Kanuri','','','kr','kau','kau','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (2776,'kk','ltr','Kazakh','','','kk','kaz','kaz','\0','Қазақ','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (2939,'km','ltr','Khmer','','','km','khm','khm','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (2963,'ki','ltr','Kikuyu','','','ki','kik','kik','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (2966,'rw','ltr','Kinyarwanda','','','rw','kin','kin','\0','Kinyarwanda','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (2970,'ky','ltr','Kirghiz','','','ky','kir','kir','\0','Кыргыз','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (3117,'kv','ltr','Komi','','','kv','kom','kom','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (3118,'kg','ltr','Kongo','','','kg','kon','kon','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (3122,'ko','ltr','Korean','','','ko','kor','kor','\0','한국어','','','c = 1',NULL,'L');
INSERT INTO `globalize_languages` VALUES (3260,'kj','ltr','Kuanyama','','','kj','kua','kua','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (3276,'ku','ltr','Kurdish','','','ku','kur','kur','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (3428,'lo','ltr','Lao','','','lo','lao','lao','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (3433,'la','ltr','Latin','','','la','lat','lat','\0','','','','',NULL,'A');
INSERT INTO `globalize_languages` VALUES (3435,'lv','ltr','Latvian','','','lv','lav','lav','\0','Latviešu','','','c%10==1 && c%100!=11 ? 1 : c != 0 ? 2 : 3',NULL,'L');
INSERT INTO `globalize_languages` VALUES (3546,'li','ltr','Limburgish','','Limburger','li','lim','lim','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (3547,'ln','ltr','Lingala','','','ln','lin','lin','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (3553,'lt','ltr','Lithuanian','','','lt','lit','lit','\0','Lietuviškai','','','c%10==1 && c%100!=11 ? 1 : c%10>=2 && (c%100<10 || c%100>=20) ? 2 : 3',NULL,'L');
INSERT INTO `globalize_languages` VALUES (3687,'lb','ltr','Letzeburgesch','','','lb','ltz','ltz','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (3689,'lu','ltr','Luba-Katanga','','','lu','lub','lub','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (3694,'lg','ltr','Ganda','','','lg','lug','lug','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (3732,'mh','ltr','Marshall','','','mh','mah','mah','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (3736,'ml','ltr','Malayalam','','','ml','mal','mal','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (3740,'mr','ltr','Marathi','','','mr','mar','mar','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (3981,'mk','ltr','Macedonian','','','mk','mkd','mkd','\0','Македонски','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (4009,'mg','ltr','Malagasy','','','mg','mlg','mlg','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (4022,'mt','ltr','Maltese','','','mt','mlt','mlt','\0','Malti','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (4091,'mo','ltr','Moldavian','','','mo','mol','mol','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (4093,'mn','ltr','Mongolian','','','mn','mon','mon','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (4166,'mi','ltr','Maori','','','mi','mri','mri','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (4184,'ms','ltr','Malay','generic','','ms','msa','msa','\0','Bahasa melayu','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (4338,'my','ltr','Burmese','','','my','mya','mya','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (4406,'na','ltr','Nauru','','','na','nau','nau','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (4407,'nv','ltr','Navajo','','','nv','nav','nav','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (4423,'nr','ltr','Ndebele','','South','nr','nbl','nbl','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (4463,'nd','ltr','Ndebele','','North','nd','nde','nde','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (4473,'ng','ltr','Ndonga','','','ng','ndo','ndo','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (4499,'ne','ltr','Nepali','','','ne','nep','nep','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (4628,'nl','ltr','Dutch','','','nl','nld','nld','\0','Nederlands','','','c == 1 ? 1 : 2',NULL,'L');
INSERT INTO `globalize_languages` VALUES (4682,'nn','ltr','Norwegian Nynorsk','','','nn','nno','nno','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (4695,'nb','ltr','Norwegian Bokmål','','','nb','nob','nob','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (4709,'no','ltr','Norwegian','','','no','nor','nor','\0','Norsk','','','c == 1 ? 1 : 2',NULL,'L');
INSERT INTO `globalize_languages` VALUES (4821,'ny','ltr','Chichewa; Nyanja','','','ny','nya','nya','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (4867,'oc','ltr','Occitan','post 1500','','oc','oci','oci','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (4891,'oj','ltr','Ojibwa','','','oj','oji','oji','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (4965,'or','ltr','Oriya','','','or','ori','ori','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (4967,'om','ltr','Oromo','','','om','orm','orm','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (4984,'os','ltr','Ossetian; Ossetic','','','os','oss','oss','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (5031,'pa','ltr','Panjabi','','','pa','pan','pan','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (5176,'pi','ltr','Pali','','','pi','pli','pli','\0','','','','',NULL,'A');
INSERT INTO `globalize_languages` VALUES (5244,'pl','ltr','Polish','','','pl','pol','pol','\0','Polski','','','c==1 ? 1 : c%10>=2 && c%10<=4 && (c%100<10 || c%100>=20) ? 2 : 3',NULL,'L');
INSERT INTO `globalize_languages` VALUES (5250,'pt','ltr','Portuguese','','','pt','por','por','\0','português','','','c == 1 ? 1 : 2',NULL,'L');
INSERT INTO `globalize_languages` VALUES (5343,'ps','ltr','Pushto','','','ps','pus','pus','\0','پښتو','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (5368,'qu','ltr','Quechua','','','qu','que','que','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (5525,'rm','ltr','Raeto-Romance','','','rm','roh','roh','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (5528,'ro','ltr','Romanian','','','ro','ron','ron','\0','Română','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (5552,'rn','ltr','Rundi','','','rn','run','run','\0','Kirundi','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (5556,'ru','ltr','Russian','','','ru','rus','rus','\0','Pyccĸий','','','c%10==1 && c%100!=11 ? 1 : c%10>=2 && c%10<=4 && (c%100<10 || c%100>=20) ? 2 : 3',NULL,'L');
INSERT INTO `globalize_languages` VALUES (5576,'sg','ltr','Sango','','','sg','sag','sag','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (5581,'sa','ltr','Sanskrit','','','sa','san','san','\0','','','','',NULL,'A');
INSERT INTO `globalize_languages` VALUES (5738,'si','ltr','Sinhalese','','','si','sin','sin','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (5800,'sk','ltr','Slovak','','','sk','slk','slk','\0','Slovenčina','','','c%10==1 && c%100!=11 ? 1 : c%10>=2 && c%10<=4 && (c%100<10 || c%100>=20) ? 2 : 3',NULL,'L');
INSERT INTO `globalize_languages` VALUES (5810,'sl','ltr','Slovenian','','','sl','slv','slv','\0','Slovenščina','','','c%100==1 ? 1 : c%100==2 ? 2 : c%100==3 || c%100==4 ? 3 : 4',NULL,'L');
INSERT INTO `globalize_languages` VALUES (5819,'se','ltr','Northern Sami','','','se','sme','sme','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (5828,'sm','ltr','Samoan','','','sm','smo','smo','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (5840,'sn','ltr','Shona','','','sn','sna','sna','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (5843,'sd','ltr','Sindhi','','','sd','snd','snd','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (5876,'so','ltr','Somali','','','so','som','som','\0','Somali','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (5882,'st','ltr','Sotho','','Southern','st','sot','sot','\0','','','','',NULL,'L');
/* INSERT INTO `globalize_languages` VALUES (5889,'es','ltr','Spanish','','','es','spa','spa','\0','Español','','','c == 1 ? 1 : 2','',NULL'); */
INSERT INTO `globalize_languages` VALUES (5910,'sq','ltr','Albanian','','','sq','sqi','sqi','\0','shqip','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (5921,'sc','ltr','Sardinian','','','sc','srd','srd','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (5933,'sr','ltr','Serbian','','','sr','srp','srp','\0','Srpski','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (5964,'ss','ltr','Swati','','','ss','ssw','ssw','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (6002,'su','ltr','Sundanese','','','su','sun','sun','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (6021,'sw','ltr','Swahili','generic','','sw','swa','swa','\0','Kiswahili','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (6024,'sv','ltr','Swedish','','','sv','swe','swe','\0','svenska','','','c == 1 ? 1 : 2',NULL,'L');
INSERT INTO `globalize_languages` VALUES (6086,'ty','ltr','Tahitian','','','ty','tah','tah','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (6090,'ta','ltr','Tamil','','','ta','tam','tam','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (6097,'tt','ltr','Tatar','','','tt','tat','tat','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (6182,'te','ltr','Telugu','','','te','tel','tel','\0','తెలుగు','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (6210,'tg','ltr','Tajik','','','tg','tgk','tgk','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (6211,'tl','ltr','Tagalog','','','tl','tgl','tgl','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (6223,'th','ltr','Thai','','','th','tha','tha','\0','ภาษาไทย','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (6260,'ti','ltr','Tigrinya','','','ti','tir','tir','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (6383,'to','ltr','Tonga','Tonga Islands','','to','ton','ton','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (6466,'tn','ltr','Tswana','','','tn','tsn','tsn','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (6467,'ts','ltr','Tsonga','','','ts','tso','tso','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (6513,'tk','ltr','Turkmen','','','tk','tuk','tuk','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (6519,'tr','ltr','Turkish','','','tr','tur','tur','\0','Tϋrkçe','','','c = 1',NULL,'L');
INSERT INTO `globalize_languages` VALUES (6546,'tw','ltr','Twi','','','tw','twi','twi','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (6630,'ug','ltr','Uighur','','','ug','uig','uig','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (6640,'uk','ltr','Ukrainian','','','uk','ukr','ukr','\0','Українська','','','c%10==1 && c%100!=11 ? 1 : c%10>=2 && c%10<=4 && (c%100<10 || c%100>=20) ? 2 : 3',NULL,'L');
INSERT INTO `globalize_languages` VALUES (6679,'ur','ltr','Urdu','','','ur','urd','urd','\0','اردو','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (6719,'uz','ltr','Uzbek','','','uz','uzb','uzb','\0',"o'zbek",'','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (6744,'ve','ltr','Venda','','','ve','ven','ven','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (6751,'vi','ltr','Vietnamese','','','vi','vie','vie','\0','Tiếng Việt','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (6800,'vo','ltr','Volapük','','','vo','vol','vol','\0','','','','',NULL,'C');
INSERT INTO `globalize_languages` VALUES (6911,'wa','ltr','Walloon','','','wa','wln','wln','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (6952,'wo','ltr','Wolof','','','wo','wol','wol','\0','Wolof','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (7078,'xh','ltr','Xhosa','','','xh','xho','xho','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (7324,'yi','ltr','Yiddish','','','yi','yid','yid','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (7481,'za','ltr','Zhuang','','','za','zha','zha','\0','','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (7484,'zh','ltr','Chinese','','','zh','zho','zho','\0','中文','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (7594,'zu','ltr','Zulu','','','zu','zul','zul','\0','isiZulu','','','',NULL,'L');
INSERT INTO `globalize_languages` VALUES (7595,'zh-Hant','ltr','Traditional Chinese','','','',NULL,NULL,'\0','','','','','zh-Hant','L');
INSERT INTO `globalize_languages` VALUES (7596,'zh-Hans','ltr','Simplified Chinese','','','',NULL,NULL,'\0','','','','','zh-Hans','L');
