INSERT INTO `globalize_countries` VALUES (1,'AD','EUR','','','','','Andorra','western','');
INSERT INTO `globalize_countries` VALUES (2,'AE','AED','.','','','.','United Arab Emirates','western',',');
INSERT INTO `globalize_countries` VALUES (3,'AF','AFA','','','','','Afghanistan','western','');
INSERT INTO `globalize_countries` VALUES (4,'AG','XCD','','','','','Antigua and Barbuda','western','');
INSERT INTO `globalize_countries` VALUES (5,'AI','XCD','','','','','Anguilla','western','');
INSERT INTO `globalize_countries` VALUES (6,'AL','ALL',',','','',',','Albania','western','.');
INSERT INTO `globalize_countries` VALUES (7,'AM','AMD','','','','','Armenia','western','');
INSERT INTO `globalize_countries` VALUES (8,'AN','ANG','','','','','Netherlands Antilles','western','');
INSERT INTO `globalize_countries` VALUES (9,'AO','AON','','','','','Angola','western','');
INSERT INTO `globalize_countries` VALUES (10,'AQ','NOK','','','','','Antarctica','western','');
INSERT INTO `globalize_countries` VALUES (11,'AR','ARA',',','','',',','Argentina','western','.');
INSERT INTO `globalize_countries` VALUES (12,'AS','USD','','','','','American Samoa','western','');
INSERT INTO `globalize_countries` VALUES (13,'AT','EUR',',','€ %n','',',','Austria','western','');
INSERT INTO `globalize_countries` VALUES (14,'AU','AUD','.','','','.','Australia','western',',');
INSERT INTO `globalize_countries` VALUES (15,'AW','AWG','','','','','Aruba','western','');
INSERT INTO `globalize_countries` VALUES (16,'AZ','AZM','.','','','.','Azerbaijan','western','');
INSERT INTO `globalize_countries` VALUES (17,'BA','BAM',',','','',',','Bosnia and Herzegovina','western','');
INSERT INTO `globalize_countries` VALUES (18,'BB','BBD','','','','','Barbados','western','');
INSERT INTO `globalize_countries` VALUES (19,'BD','BDT','.','','','.','Bangladesh','western',',');
INSERT INTO `globalize_countries` VALUES (20,'BE','EUR',',','%n €','',',','Belgium','western','.');
INSERT INTO `globalize_countries` VALUES (21,'BF','XAF','','','','','Burkina Faso','western','');
INSERT INTO `globalize_countries` VALUES (22,'BG','BGL',',','','',',','Bulgaria','western',' ');
INSERT INTO `globalize_countries` VALUES (23,'BH','BHD','.','','','.','Bahrain','western',',');
INSERT INTO `globalize_countries` VALUES (24,'BI','BIF','','','','','Burundi','western','');
INSERT INTO `globalize_countries` VALUES (25,'BJ','XAF','','','','','Benin','western','');
INSERT INTO `globalize_countries` VALUES (26,'BM','BMD','','','','','Bermuda','western','');
INSERT INTO `globalize_countries` VALUES (27,'BN','BND','','','','','Brunei Darussalam','western','');
INSERT INTO `globalize_countries` VALUES (28,'BO','BOB',',','','',',','Bolivia','western','.');
INSERT INTO `globalize_countries` VALUES (29,'BR','BRR',',','R$%n','',',','Brazil','western','.');
INSERT INTO `globalize_countries` VALUES (30,'BS','BSD','','','','','Bahamas','western','');
INSERT INTO `globalize_countries` VALUES (31,'BT','BTN','','','','','Bhutan','western','');
INSERT INTO `globalize_countries` VALUES (32,'BV','NOK','','','','','Bouvet Island','western','');
INSERT INTO `globalize_countries` VALUES (33,'BW','BWP','.','','','.','Botswana','western',',');
INSERT INTO `globalize_countries` VALUES (34,'BY','BYR','.','','','.','Belarus','western','');
INSERT INTO `globalize_countries` VALUES (35,'BZ','BZD','','','','','Belize','western','');
INSERT INTO `globalize_countries` VALUES (36,'CA','CAD','.','','','.','Canada','western',',');
INSERT INTO `globalize_countries` VALUES (37,'CC','AUD','','','','','Cocos  Islands','western','');
INSERT INTO `globalize_countries` VALUES (38,'CD','','','','','','Congo','western','');
INSERT INTO `globalize_countries` VALUES (39,'CF','XAF','','','','','Central African Republic','western','');
INSERT INTO `globalize_countries` VALUES (40,'CG','XAF','','','','','Congo','western','');
INSERT INTO `globalize_countries` VALUES (41,'CH','CHF','.','SFr. %n','',',','Switzerland','western',"'");
INSERT INTO `globalize_countries` VALUES (42,'CI','XAF','','','','',"Cote D'Ivoire",'western','');
INSERT INTO `globalize_countries` VALUES (43,'CK','NZD','','','','','Cook Islands','western','');
INSERT INTO `globalize_countries` VALUES (44,'CL','CLF',',','','',',','Chile','western','.');
INSERT INTO `globalize_countries` VALUES (45,'CM','XAF','','','','','Cameroon','western','');
INSERT INTO `globalize_countries` VALUES (46,'CN','CNY','.','Y%n','','.','China','western',',');
INSERT INTO `globalize_countries` VALUES (47,'CO','COP',',','','',',','Colombia','western','.');
INSERT INTO `globalize_countries` VALUES (48,'CR','CRC','.','','','.','Costa Rica','western',',');
INSERT INTO `globalize_countries` VALUES (49,'CS','CSD','','','','','Serbia and Montenegro','western','');
INSERT INTO `globalize_countries` VALUES (50,'CU','CUP','','','','','Cuba','western','');
INSERT INTO `globalize_countries` VALUES (51,'CV','CVE','','','','','Cape Verde','western','');
INSERT INTO `globalize_countries` VALUES (52,'CX','AUD','','','','','Christmas Island','western','');
INSERT INTO `globalize_countries` VALUES (53,'CY','CYP','','','','','Cyprus','western','');
INSERT INTO `globalize_countries` VALUES (54,'CZ','CZK',',','','',',','Czech Republic','western',' ');
INSERT INTO `globalize_countries` VALUES (55,'DE','EUR',',','%n €','',',','Germany','western','.');
INSERT INTO `globalize_countries` VALUES (56,'DJ','DJF','','','','','Djibouti','western','');
INSERT INTO `globalize_countries` VALUES (57,'DK','DKK',',','','',',','Denmark','western','.');
INSERT INTO `globalize_countries` VALUES (58,'DM','XCD','','','','','Dominica','western','');
INSERT INTO `globalize_countries` VALUES (59,'DO','DOP','.','','','.','Dominican Republic','western',',');
INSERT INTO `globalize_countries` VALUES (60,'DZ','DZD','.','','','.','Algeria','western',',');
INSERT INTO `globalize_countries` VALUES (61,'EC','USD',',','','',',','Ecuador','western','.');
INSERT INTO `globalize_countries` VALUES (62,'EE','EEK',',','','',',','Estonia','western',' ');
INSERT INTO `globalize_countries` VALUES (63,'EG','EGP','.','','','.','Egypt','western',',');
INSERT INTO `globalize_countries` VALUES (64,'EH','MAD','','','','','Western Sahara','western','');
INSERT INTO `globalize_countries` VALUES (65,'ER','ERN','.','','','.','Eritrea','western',',');
INSERT INTO `globalize_countries` VALUES (66,'ES','EUR',',','%n €','',',','Spain','western','.');
INSERT INTO `globalize_countries` VALUES (67,'ET','ETB','.','','','.','Ethiopia','western',',');
INSERT INTO `globalize_countries` VALUES (68,'FI','EUR',',','','',',','Finland','western',' ');
INSERT INTO `globalize_countries` VALUES (69,'FJ','FJD','','','','','Fiji','western','');
INSERT INTO `globalize_countries` VALUES (70,'FK','FKP','','','','','Falkland Islands','western','');
INSERT INTO `globalize_countries` VALUES (71,'FM','USD','','','','','Micronesia','western','');
INSERT INTO `globalize_countries` VALUES (72,'FO','DKK',',','','',',','Faeroe Islands','western','.');
INSERT INTO `globalize_countries` VALUES (73,'FR','EUR',',','%n €','',',','France','western','');
INSERT INTO `globalize_countries` VALUES (74,'GA','XAF','','','','','Gabon','western','');
/* INSERT INTO `globalize_countries` VALUES (75,'GB','GBP','.','£%n','','.','United Kingdom','western',','); */
INSERT INTO `globalize_countries` VALUES (76,'GD','XCD','','','','','Grenada','western','');
INSERT INTO `globalize_countries` VALUES (77,'GE','GEL',',','','',',','Georgia','western','.');
INSERT INTO `globalize_countries` VALUES (78,'GF','EUR','','','','','French Guiana','western','');
INSERT INTO `globalize_countries` VALUES (79,'GH','GHC','','','','','Ghana','western','');
INSERT INTO `globalize_countries` VALUES (80,'GI','GIP','','','','','Gibraltar','western','');
INSERT INTO `globalize_countries` VALUES (81,'GL','DKK',',','','',',','Greenland','western','.');
INSERT INTO `globalize_countries` VALUES (82,'GM','GMD','','','','','Gambia','western','');
INSERT INTO `globalize_countries` VALUES (83,'GN','GNS','','','','','Guinea','western','');
INSERT INTO `globalize_countries` VALUES (84,'GP','EUR','','','','','Guadaloupe','western','');
INSERT INTO `globalize_countries` VALUES (85,'GQ','XAF','','','','','Equatorial Guinea','western','');
INSERT INTO `globalize_countries` VALUES (86,'GR','EUR',',','','',',','Greece','western','.');
INSERT INTO `globalize_countries` VALUES (87,'GS','GBP','','','','','South Georgia and the South Sandwich Islands','western','');
INSERT INTO `globalize_countries` VALUES (88,'GT','GTQ','.','','','.','Guatemala','western',',');
INSERT INTO `globalize_countries` VALUES (89,'GU','USD','','','','','Guam','western','');
INSERT INTO `globalize_countries` VALUES (90,'GW','GWP','','','','','Guinea-Bissau','western','');
INSERT INTO `globalize_countries` VALUES (91,'GY','GYD','','','','','Guyana','western','');
INSERT INTO `globalize_countries` VALUES (92,'HK','HKD','.','HK$%n','','.','Hong Kong','western',',');
INSERT INTO `globalize_countries` VALUES (93,'HM','AUD','','','','','Heard and McDonald Islands','western','');
INSERT INTO `globalize_countries` VALUES (94,'HN','HNL','.','','','.','Honduras','western',',');
INSERT INTO `globalize_countries` VALUES (95,'HR','HRK',',','','',',','Hrvatska','western','');
INSERT INTO `globalize_countries` VALUES (96,'HT','HTG','','','','','Haiti','western','');
INSERT INTO `globalize_countries` VALUES (97,'HU','HUF',',','','',',','Hungary','western','.');
INSERT INTO `globalize_countries` VALUES (98,'ID','IDR',',','','',',','Indonesia','western','.');
INSERT INTO `globalize_countries` VALUES (99,'IE','EUR','.','','','.','Ireland','western',',');
INSERT INTO `globalize_countries` VALUES (100,'IL','ILS','.','%n ₪','','.','Israel','western',',');
INSERT INTO `globalize_countries` VALUES (101,'IN','INR','.','Rs.%n','','.','India','indian',',');
INSERT INTO `globalize_countries` VALUES (102,'IO','GBP','','','','','British Indian Ocean Territory','western','');
INSERT INTO `globalize_countries` VALUES (103,'IQ','IQD','.','','','.','Iraq','western',',');
INSERT INTO `globalize_countries` VALUES (104,'IR','IRR','٫','','','٫','Iran','western','٬');
INSERT INTO `globalize_countries` VALUES (105,'IS','ISK',',','','',',','Iceland','western','.');
INSERT INTO `globalize_countries` VALUES (106,'IT','EUR',',','€ %n','',',','Italy','western','.');
INSERT INTO `globalize_countries` VALUES (107,'JM','JMD','','','','','Jamaica','western','');
INSERT INTO `globalize_countries` VALUES (108,'JO','JOD','.','','','.','Jordan','western',',');
INSERT INTO `globalize_countries` VALUES (109,'JP','JPY','.','¥%n','','.','Japan','western',',');
INSERT INTO `globalize_countries` VALUES (110,'KE','KES','','','','','Kenya','western','');
INSERT INTO `globalize_countries` VALUES (111,'KG','KGS','','','','','Kyrgyz Republic','western','');
INSERT INTO `globalize_countries` VALUES (112,'KH','KHR','','','','','Cambodia','western','');
INSERT INTO `globalize_countries` VALUES (113,'KI','AUD','','','','','Kiribati','western','');
INSERT INTO `globalize_countries` VALUES (114,'KM','KMF','','','','','Comoros','western','');
INSERT INTO `globalize_countries` VALUES (115,'KN','XCD','','','','','St. Kitts and Nevis','western','');
INSERT INTO `globalize_countries` VALUES (116,'KP','KPW','','','','','Korea','western','');
INSERT INTO `globalize_countries` VALUES (117,'KR','KRW','.','','','.','Korea','western',',');
INSERT INTO `globalize_countries` VALUES (118,'KW','KWD','.','','','.','Kuwait','western',',');
INSERT INTO `globalize_countries` VALUES (119,'KY','KYD','','','','','Cayman Islands','western','');
INSERT INTO `globalize_countries` VALUES (120,'KZ','KZT','','','','','Kazakhstan','western','');
INSERT INTO `globalize_countries` VALUES (121,'LA','LAK','.','','','.',"Lao People's Democratic Republic",'western',',');
INSERT INTO `globalize_countries` VALUES (122,'LB','LBP','.','','','.','Lebanon','western',',');
INSERT INTO `globalize_countries` VALUES (123,'LC','XCD','','','','','St. Lucia','western','');
INSERT INTO `globalize_countries` VALUES (124,'LI','CHF','','','','','Liechtenstein','western','');
INSERT INTO `globalize_countries` VALUES (125,'LK','LKR','','','','','Sri Lanka','western','');
INSERT INTO `globalize_countries` VALUES (126,'LR','LRD','','','','','Liberia','western','');
INSERT INTO `globalize_countries` VALUES (127,'LS','LSL','','','','','Lesotho','western','');
INSERT INTO `globalize_countries` VALUES (128,'LT','LTL',',','','',',','Lithuania','western','.');
INSERT INTO `globalize_countries` VALUES (129,'LU','EUR',',','','',',','Luxembourg','western','.');
INSERT INTO `globalize_countries` VALUES (130,'LV','LVL',',','','',',','Latvia','western',' ');
INSERT INTO `globalize_countries` VALUES (131,'LY','LYD','.','','','.','Libyan Arab Jamahiriya','western',',');
INSERT INTO `globalize_countries` VALUES (132,'MA','MAD','.','','','.','Morocco','western',',');
INSERT INTO `globalize_countries` VALUES (133,'MC','EUR','','','','','Monaco','western','');
INSERT INTO `globalize_countries` VALUES (134,'MD','MDL','','','','','Moldova','western','');
INSERT INTO `globalize_countries` VALUES (135,'MG','MGF','','','','','Madagascar','western','');
INSERT INTO `globalize_countries` VALUES (136,'MH','USD','','','','','Marshall Islands','western','');
INSERT INTO `globalize_countries` VALUES (137,'MK','MKD',',','','',',','Macedonia','western','');
INSERT INTO `globalize_countries` VALUES (138,'ML','XAF','','','','','Mali','western','');
INSERT INTO `globalize_countries` VALUES (139,'MM','','','','','','Myanmar','western','');
INSERT INTO `globalize_countries` VALUES (140,'MN','MNT','.','','','.','Mongolia','western','');
INSERT INTO `globalize_countries` VALUES (141,'MO','MOP','','','','','Macao','western','');
INSERT INTO `globalize_countries` VALUES (142,'MP','USD','','','','','Northern Mariana Islands','western','');
INSERT INTO `globalize_countries` VALUES (143,'MQ','EUR','','','','','Martinique','western','');
INSERT INTO `globalize_countries` VALUES (144,'MR','MRO','','','','','Mauritania','western','');
INSERT INTO `globalize_countries` VALUES (145,'MS','XCD','','','','','Montserrat','western','');
INSERT INTO `globalize_countries` VALUES (146,'MT','MTL','.','','','.','Malta','western',',');
INSERT INTO `globalize_countries` VALUES (147,'MU','MUR','','','','','Mauritius','western','');
INSERT INTO `globalize_countries` VALUES (148,'MV','MVR','','','','','Maldives','western','');
INSERT INTO `globalize_countries` VALUES (149,'MW','MWK','','','','','Malawi','western','');
INSERT INTO `globalize_countries` VALUES (150,'MX','MXN','.','','','.','Mexico','western',',');
INSERT INTO `globalize_countries` VALUES (151,'MY','MYR','.','','','.','Malaysia','western',',');
INSERT INTO `globalize_countries` VALUES (152,'MZ','MZM','','','','','Mozambique','western','');
INSERT INTO `globalize_countries` VALUES (153,'NA','NAD','','','','','Namibia','western','');
INSERT INTO `globalize_countries` VALUES (154,'NC','XPF','','','','','New Caledonia','western','');
INSERT INTO `globalize_countries` VALUES (155,'NE','XOF','','','','','Niger','western','');
INSERT INTO `globalize_countries` VALUES (156,'NF','AUD','','','','','Norfolk Island','western','');
INSERT INTO `globalize_countries` VALUES (157,'NG','NGN','','','','','Nigeria','western','');
INSERT INTO `globalize_countries` VALUES (158,'NI','NIC','.','','','.','Nicaragua','western',',');
INSERT INTO `globalize_countries` VALUES (159,'NL','EUR',',','€ %n','',',','Netherlands','western','');
INSERT INTO `globalize_countries` VALUES (160,'NO','NOK',',','kr %n','',',','Norway','western',' ');
INSERT INTO `globalize_countries` VALUES (161,'NP','NPR','.','','','.','Nepal','western',',');
INSERT INTO `globalize_countries` VALUES (162,'NR','AUD','','','','','Nauru','western','');
INSERT INTO `globalize_countries` VALUES (163,'NU','NZD','','','','','Niue','western','');
INSERT INTO `globalize_countries` VALUES (164,'NZ','NZD','.','','','.','New Zealand','western',',');
INSERT INTO `globalize_countries` VALUES (165,'OM','OMR','.','','','.','Oman','western',',');
INSERT INTO `globalize_countries` VALUES (166,'PA','PAB','.','','','.','Panama','western',',');
INSERT INTO `globalize_countries` VALUES (167,'PE','PEI','.','','','.','Peru','western',',');
INSERT INTO `globalize_countries` VALUES (168,'PF','XPF','','','','','French Polynesia','western','');
INSERT INTO `globalize_countries` VALUES (169,'PG','PGK','','','','','Papua New Guinea','western','');
INSERT INTO `globalize_countries` VALUES (170,'PH','PHP','.','','','.','Philippines','western',',');
INSERT INTO `globalize_countries` VALUES (171,'PK','PKR','.','','','.','Pakistan','western',',');
INSERT INTO `globalize_countries` VALUES (172,'PL','PLN',',','','',',','Poland','western','.');
INSERT INTO `globalize_countries` VALUES (173,'PM','EUR','','','','','St. Pierre and Miquelon','western','');
INSERT INTO `globalize_countries` VALUES (174,'PN','NZD','','','','','Pitcairn Island','western','');
INSERT INTO `globalize_countries` VALUES (175,'PR','USD','.','','','.','Puerto Rico','western',',');
INSERT INTO `globalize_countries` VALUES (176,'PS','','','','','','Palestinian Territory','western','');
INSERT INTO `globalize_countries` VALUES (177,'PT','EUR','$','%n €','','$','Portugal','western','.');
INSERT INTO `globalize_countries` VALUES (178,'PW','USD','','','','','Palau','western','');
INSERT INTO `globalize_countries` VALUES (179,'PY','PYG',',','','',',','Paraguay','western','.');
INSERT INTO `globalize_countries` VALUES (180,'QA','QAR','.','','','.','Qatar','western',',');
INSERT INTO `globalize_countries` VALUES (181,'RE','EUR','','','','','Reunion','western','');
INSERT INTO `globalize_countries` VALUES (182,'RO','ROL',',','','',',','Romania','western','.');
INSERT INTO `globalize_countries` VALUES (183,'RU','RUB','.','','','.','Russian Federation','western','');
INSERT INTO `globalize_countries` VALUES (184,'RW','RWF','','','','','Rwanda','western','');
INSERT INTO `globalize_countries` VALUES (185,'SA','SAR','.','','','.','Saudi Arabia','western','');
INSERT INTO `globalize_countries` VALUES (186,'SB','SBD','','','','','Solomon Islands','western','');
INSERT INTO `globalize_countries` VALUES (187,'SC','SCR','','','','','Seychelles','western','');
INSERT INTO `globalize_countries` VALUES (188,'SD','SDP','.','','','.','Sudan','western',',');
INSERT INTO `globalize_countries` VALUES (189,'SE','SEK',',','%n kr','',',','Sweden','western','');
INSERT INTO `globalize_countries` VALUES (190,'SG','SGD','.','','','.','Singapore','western',',');
INSERT INTO `globalize_countries` VALUES (191,'SH','SHP','','','','','St. Helena','western','');
INSERT INTO `globalize_countries` VALUES (192,'SI','SIT',',','','',',','Slovenia','western','');
INSERT INTO `globalize_countries` VALUES (193,'SJ','NOK','','','','','Svalbard & Jan Mayen Islands','western','');
INSERT INTO `globalize_countries` VALUES (194,'SK','SKK',',','','',',','Slovakia','western',' ');
INSERT INTO `globalize_countries` VALUES (195,'SL','SLL','','','','','Sierra Leone','western','');
INSERT INTO `globalize_countries` VALUES (196,'SM','EUR','','','','','San Marino','western','');
INSERT INTO `globalize_countries` VALUES (197,'SN','XOF','','','','','Senegal','western','');
INSERT INTO `globalize_countries` VALUES (198,'SO','SOS','','','','','Somalia','western','');
INSERT INTO `globalize_countries` VALUES (199,'SR','SRG','','','','','Suriname','western','');
INSERT INTO `globalize_countries` VALUES (200,'ST','STD','','','','','Sao Tome and Principe','western','');
INSERT INTO `globalize_countries` VALUES (201,'SV','SVC','.','','','.','El Salvador','western',',');
INSERT INTO `globalize_countries` VALUES (202,'SY','SYP','.','','','.','Syrian Arab Republic','western',',');
INSERT INTO `globalize_countries` VALUES (203,'SZ','SZL','','','','','Swaziland','western','');
INSERT INTO `globalize_countries` VALUES (204,'TC','USD','','','','','Turks and Caicos Islands','western','');
INSERT INTO `globalize_countries` VALUES (205,'TD','XAF','','','','','Chad','western','');
INSERT INTO `globalize_countries` VALUES (206,'TF','EUR','','','','','French Southern Territories','western','');
INSERT INTO `globalize_countries` VALUES (207,'TG','XAF','','','','','Togo','western','');
INSERT INTO `globalize_countries` VALUES (208,'TH','THB','.','','','.','Thailand','western',',');
INSERT INTO `globalize_countries` VALUES (209,'TJ','TJR','.','','','.','Tajikistan','western','');
INSERT INTO `globalize_countries` VALUES (210,'TK','NZD','','','','','Tokelau','western','');
INSERT INTO `globalize_countries` VALUES (211,'TL','','','','','','Timor-Leste','western','');
INSERT INTO `globalize_countries` VALUES (212,'TM','TMM','','','','','Turkmenistan','western','');
INSERT INTO `globalize_countries` VALUES (213,'TN','TND','.','','','.','Tunisia','western',',');
INSERT INTO `globalize_countries` VALUES (214,'TO','TOP','','','','','Tonga','western','');
INSERT INTO `globalize_countries` VALUES (215,'TR','TRL',',','','',',','Turkey','western','.');
INSERT INTO `globalize_countries` VALUES (216,'TT','TTD','','','','','Trinidad and Tobago','western','');
INSERT INTO `globalize_countries` VALUES (217,'TV','AUD','','','','','Tuvalu','western','');
INSERT INTO `globalize_countries` VALUES (218,'TW','TWD','.','NT$%n','','.','Taiwan','western',',');
INSERT INTO `globalize_countries` VALUES (219,'TZ','TZS','','','','','Tanzania','western','');
INSERT INTO `globalize_countries` VALUES (220,'UA','UAH','.','','','.','Ukraine','western','');
INSERT INTO `globalize_countries` VALUES (221,'UG','UGS','.','','','.','Uganda','western',',');
INSERT INTO `globalize_countries` VALUES (222,'UM','USD','','','','','United States Minor Outlying Islands','western','');
INSERT INTO `globalize_countries` VALUES (223,'US','USD','.','','','.','United States of America','western',',');
INSERT INTO `globalize_countries` VALUES (224,'UY','UYU',',','','',',','Uruguay','western','.');
INSERT INTO `globalize_countries` VALUES (225,'UZ','UZS','.','','','.','Uzbekistan','western',',');
INSERT INTO `globalize_countries` VALUES (226,'VA','EUR','','','','','Holy See','western','');
INSERT INTO `globalize_countries` VALUES (227,'VC','XCD','','','','','St. Vincent and the Grenadines','western','');
INSERT INTO `globalize_countries` VALUES (228,'VE','VEB',',','','',',','Venezuela','western','.');
INSERT INTO `globalize_countries` VALUES (229,'VG','USD','','','','','British Virgin Islands','western','');
INSERT INTO `globalize_countries` VALUES (230,'VI','USD','','','','','US Virgin Islands','western','');
INSERT INTO `globalize_countries` VALUES (231,'VN','VND',',','','',',','Viet Nam','western','.');
INSERT INTO `globalize_countries` VALUES (232,'VU','VUV','','','','','Vanuatu','western','');
INSERT INTO `globalize_countries` VALUES (233,'WF','XPF','','','','','Wallis and Futuna Islands','western','');
INSERT INTO `globalize_countries` VALUES (234,'WS','WST','','','','','Samoa','western','');
INSERT INTO `globalize_countries` VALUES (235,'YE','','.','','','.','Yemen','western',',');
INSERT INTO `globalize_countries` VALUES (236,'YT','EUR','','','','','Mayotte','western','');
INSERT INTO `globalize_countries` VALUES (237,'ZA','ZAR','.','','','.','South Africa','western',',');
INSERT INTO `globalize_countries` VALUES (238,'ZM','ZMK','','','','','Zambia','western','');
INSERT INTO `globalize_countries` VALUES (239,'ZW','ZWD','.','','','.','Zimbabwe','western',',');
