/*
 *
 * Copyright (C) 2007 The kune development team (see CREDITS for details)
 * This file is part of kune.
 *
 * Kune is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * Kune is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

package org.ourproject.kune.platf.server.domain;

import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.search.annotations.DocumentId;
import org.hibernate.search.annotations.Indexed;

import com.google.inject.name.Named;
import com.wideplay.warp.persist.dao.Finder;

/**
 * GlobalizeTranslations generated by hbm2java from original rails globalize
 * schema
 */
@Entity
@Indexed
@Table(name = "globalize_translations")
public class I18nTranslation implements HasId {

    public static final String DEF_NAMESPACE = "kune_core";
    public static final Integer DEF_PLUR_INDEX = 1;
    public static final String DEFAULT_LANG = "en";
    public static final String UNTRANSLATED_VALUE = null;

    @Id
    @GeneratedValue
    @DocumentId
    @Column(name = "id", unique = true, nullable = false)
    private Long id;

    @Column(name = "type")
    private String type;

    @Column(name = "tr_key")
    private String trKey;

    @Column(name = "table_name")
    private String tableName;

    @Column(name = "item_id")
    private Integer itemId;

    @Column(name = "facet")
    private String facet;

    @ManyToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "language_id")
    private I18nLanguage language;

    @Column(name = "pluralization_index")
    private Integer pluralizationIndex;

    @Column(name = "text")
    private String text;

    public I18nTranslation() {
        this(null, null, null, null, null, null, null, null);
    }

    public I18nTranslation(final String type, final String trKey, final String tableName, final Integer itemId,
            final String facet, final I18nLanguage language, final String text, final Integer pluralizationIndex) {
        this.type = type;
        this.trKey = trKey;
        this.tableName = tableName;
        this.itemId = itemId;
        this.facet = facet;
        this.language = language;
        this.pluralizationIndex = pluralizationIndex;
        this.text = text;
    }

    public I18nTranslation(final String trKey, final I18nLanguage language, final String text) {
        this(DEF_NAMESPACE, trKey, "", null, "", language, text, DEF_PLUR_INDEX);
    }

    public Long getId() {
        return this.id;
    }

    public void setId(final Long id) {
        this.id = id;
    }

    public String getType() {
        return this.type;
    }

    public void setType(final String type) {
        this.type = type;
    }

    public String getTrKey() {
        return this.trKey;
    }

    public void setTrKey(final String trKey) {
        this.trKey = trKey;
    }

    public String getTableName() {
        return this.tableName;
    }

    public void setTableName(final String tableName) {
        this.tableName = tableName;
    }

    public Integer getItemId() {
        return this.itemId;
    }

    public void setItemId(final Integer itemId) {
        this.itemId = itemId;
    }

    public String getFacet() {
        return this.facet;
    }

    public void setFacet(final String facet) {
        this.facet = facet;
    }

    public Integer getPluralizationIndex() {
        return this.pluralizationIndex;
    }

    public void setPluralizationIndex(final Integer pluralizationIndex) {
        this.pluralizationIndex = pluralizationIndex;
    }

    public String getText() {
        return this.text;
    }

    public void setText(final String text) {
        this.text = text;
    }

    public I18nLanguage getLanguage() {
        return language;
    }

    public void setLanguage(final I18nLanguage language) {
        this.language = language;
    }

    @Finder(query = "SELECT gt FROM I18nTranslation gt JOIN gt.language gl WHERE gl.code = :language")
    public List<I18nTranslation> findByLanguage(@Named("language")
    final String language) {
        return null;
    }

}
