/*
 *
 * Copyright (C) 2007 The kune development team (see CREDITS for details)
 * This file is part of kune.
 *
 * Kune is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * Kune is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

package org.ourproject.kune.platf.server.domain;

import static javax.persistence.GenerationType.IDENTITY;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.search.annotations.DocumentId;
import org.hibernate.search.annotations.Indexed;

import com.google.inject.name.Named;
import com.wideplay.warp.persist.dao.Finder;

/**
 * GlobalizeCountries generated by hbm2java from original rails globalize schema
 */
@Entity
@Indexed
@Table(name = "globalize_countries")
public class I18nCountry implements HasId {

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @DocumentId
    @Column(name = "id", unique = true, nullable = false)
    private Long id;

    @Column(name = "code", length = 2)
    private String code;

    @Column(name = "english_name")
    private String englishName;

    @Column(name = "date_format")
    private String dateFormat;

    @Column(name = "currency_format")
    private String currencyFormat;

    @Column(name = "currency_code", length = 3)
    private String currencyCode;

    @Column(name = "thousands_sep", length = 2)
    private String thousandsSep;

    @Column(name = "decimal_sep", length = 2)
    private String decimalSep;

    @Column(name = "currency_decimal_sep", length = 2)
    private String currencyDecimalSep;

    @Column(name = "number_grouping_scheme")
    private String numberGroupingScheme;

    public I18nCountry() {
        this(null, null, null, null, null, null, null, null, null, null);
    }

    public I18nCountry(final Long id, final String code, final String englishName, final String dateFormat,
            final String currencyFormat, final String currencyCode, final String thousandsSep, final String decimalSep,
            final String currencyDecimalSep, final String numberGroupingScheme) {
        this.id = id;
        this.code = code;
        this.englishName = englishName;
        this.dateFormat = dateFormat;
        this.currencyFormat = currencyFormat;
        this.currencyCode = currencyCode;
        this.thousandsSep = thousandsSep;
        this.decimalSep = decimalSep;
        this.currencyDecimalSep = currencyDecimalSep;
        this.numberGroupingScheme = numberGroupingScheme;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(final Long id) {
        this.id = id;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(final String code) {
        this.code = code;
    }

    public String getEnglishName() {
        return this.englishName;
    }

    public void setEnglishName(final String englishName) {
        this.englishName = englishName;
    }

    public String getDateFormat() {
        return this.dateFormat;
    }

    public void setDateFormat(final String dateFormat) {
        this.dateFormat = dateFormat;
    }

    public String getCurrencyFormat() {
        return this.currencyFormat;
    }

    public void setCurrencyFormat(final String currencyFormat) {
        this.currencyFormat = currencyFormat;
    }

    public String getCurrencyCode() {
        return this.currencyCode;
    }

    public void setCurrencyCode(final String currencyCode) {
        this.currencyCode = currencyCode;
    }

    public String getThousandsSep() {
        return this.thousandsSep;
    }

    public void setThousandsSep(final String thousandsSep) {
        this.thousandsSep = thousandsSep;
    }

    public String getDecimalSep() {
        return this.decimalSep;
    }

    public void setDecimalSep(final String decimalSep) {
        this.decimalSep = decimalSep;
    }

    public String getCurrencyDecimalSep() {
        return this.currencyDecimalSep;
    }

    public void setCurrencyDecimalSep(final String currencyDecimalSep) {
        this.currencyDecimalSep = currencyDecimalSep;
    }

    public String getNumberGroupingScheme() {
        return this.numberGroupingScheme;
    }

    public void setNumberGroupingScheme(final String numberGroupingScheme) {
        this.numberGroupingScheme = numberGroupingScheme;
    }

    @Finder(query = "FROM I18nCountry")
    public List<I18nCountry> getAll() {
        return null;
    }

    @Finder(query = "FROM I18nCountry WHERE code = :country")
    public I18nCountry findByCode(@Named("country")
    final String country) {
        return null;
    }

}
