#!/bin/sh
# config maintainer script for kune-mysql

set -e 
	     
# source debconf stuff
. /usr/share/debconf/confmodule

# source dbconfig-common shell library, and call the hook function
  	 			         
if [ -f /usr/share/dbconfig-common/dpkg/config.mysql ]; then
   . /usr/share/dbconfig-common/dpkg/config.mysql 
   dbc_dbuser=kune
   dbc_dbname=kune_prod
   dbc_mysql_createdb_encoding="UTF8"
   dbc_go kune $@
fi