#!/bin/sh
# config maintainer script for kune-mysql
	     
# source debconf stuff
. /usr/share/debconf/confmodule

# source dbconfig-common shell library, and call the hook function
  	 			         
if [ -f /usr/share/dbconfig-common/dpkg/config.mysql ]; then
   . /usr/share/dbconfig-common/dpkg/config.mysql 
   dbc_go kune $@
fi