#!/bin/sh
# preinst script for kune
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <new-preinst> `install'
#        * <new-preinst> `install' <old-version>
#        * <new-preinst> `upgrade' <old-version>
#        * <old-preinst> `abort-upgrade' <new-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    install|upgrade)

    # add the kune user
    if ! getent passwd kune >/dev/null; then
      adduser --disabled-password  --quiet --system \
      --home $(KUNE) --gecos "Kune server" --group kune
    fi
    if ! getent group kune >/dev/null; then
      addgroup --system kune
    fi


    mkdir -p $(CURDIR)/etc/kune
    mkdir -p $(CURDIR)/usr/share/kune/bin
    mkdir -p $(CURDIR)/usr/share/kune/ws
    mkdir -p $(CURDIR)/usr/share/kune/lib
    mkdir -p $(CURDIR)/usr/share/kune/webapp
    mkdir -p $(CURDIR)/usr/share/kune/custom
    mkdir -p $(CURDIR)/var/lib/kune/uploads
    mkdir -p $(CURDIR)/var/lib/kune/lucene/kune_prod/indexes

    chown kune:kune $(CURDIR)/etc/kune
    chown kune:kune $(CURDIR)/usr/share/kune
    chown kune:kune $(CURDIR)/usr/share/kune/bin
    chown kune:kune $(CURDIR)/usr/share/kune/ws
    chown kune:kune $(CURDIR)/usr/share/kune/lib
    chown kune:kune $(CURDIR)/usr/share/kune/webapp
    chown kune:kune $(CURDIR)/usr/share/kune/custom
    chown kune:kune $(CURDIR)/var/lib/kune/uploads
    chown kune:kune $(CURDIR)/var/lib/kune/lucene/kune_prod/indexes

    chmod 0755 $(CURDIR)/etc/kune
    chown 0755 $(CURDIR)/usr/share/kune
    chown 0755 $(CURDIR)/usr/share/kune/ws
    chown 0755 $(CURDIR)/usr/share/kune/bin
    chown 0755 $(CURDIR)/usr/share/kune/lib
    chown 0755 $(CURDIR)/usr/share/kune/webapp
    chown 0755 $(CURDIR)/usr/share/kune/custom
    chmod 0755 $(CURDIR)/var/lib/kune/uploads
    chmod 0755 $(CURDIR)/var/lib/kune/lucene/kune_prod/indexes

    # TODO do the same (remove the user/dirs) in rm.ex

    ;;

    abort-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
